

#jwt:
#  secret : ekqpreuorqiueriqeurpeqruqoruoqure


spring:
  application:
    name: find-service
  datasource:

    url: jdbc:mysql://localhost:3306/seoul?serverTimezone=Asia/Seoul
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 0

eureka:
  instance:
    instance-id: find-instance
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka